# Exported from Render on 2026-03-05T04:17:56Z
version: "1"
projects:
  - name: My project
    environments:
      - name: Production
        databases:
          - name: denny-love-money-postgresql
            databaseName: denny_love_money_postgresql
            user: denny_love_money_postgresql_user
            plan: free
            region: oregon
            ipAllowList:
              - source: 0.0.0.0/0
                description: everywhere
            postgresMajorVersion: "18"
